project:
  name: quickstart-eks-gitlab
  shorten_stack_name: true
  template: templates/gitlab-entry-new-vpc.template.yaml
  parameters:
    KeyPairName: --overridden--
    RemoteAccessCIDR: 127.0.0.1/32
    QSS3BucketName: $[taskcat_autobucket]
    QSS3BucketRegion: $[taskcat_current_region]
    QSS3KeyPrefix: quickstart-eks-gitlab/
  lambda_source_path: functions/source
  lambda_zip_path: functions/packages
  s3_bucket: ''

tests:

  deploy-in-3-az-with-defaults:
    parameters:
      AvailabilityZones: $[taskcat_genaz_3]
      NumberOfAZs: 3
      EKSPublicAccessEndpoint: Enabled
      ProvisionBastionHost: Disabled
      DomainName: devops.$[taskcat_random-string].com
    regions:
    - eu-west-1
    - us-east-1
    - us-west-2

  deploy-in-2-az-with-optional-features:
    parameters:
      AvailabilityZones: $[taskcat_genaz_2]
      NumberOfAZs: 2
      EKSPublicAccessEndpoint: Disabled
      ProvisionBastionHost: Enabled
      DomainName: devops.$[taskcat_random-string].com
      ConfigureContainerInsights: 'Yes'
      ConfigureGrafana: 'Yes'
      CreateHostedZone: 'Yes'
      CacheMode: External
      SMTPDomain: CreateNew
      ConfigureRunner: 'Yes'
      PrivilegedMode: 'Yes'
    regions:
    - eu-central-1

  deploy-in-gov-cloud:
    parameters:
      AvailabilityZones: $[taskcat_genaz_2]
      NumberOfAZs: 2
      EKSPublicAccessEndpoint: Disabled
      ProvisionBastionHost: Disabled
      DomainName: devops.$[taskcat_random-string].dev
      ConfigureContainerInsights: 'Yes'
    regions:
      - us-gov-east-1
      - us-gov-west-1