// DarwinJS - I will need to use this from the Quick Start console after soft launch to provide any refinement.

// We need to work around Step numbers here if we are going to potentially exclude the AMI subscription
=== Reference Architecture Compliance
This default configuration will be reference complaint in the number and configuration of instances and setup of SSL and DNS, but it will deploy as small of instances as possible to control costs for a functional POC.  This means it will only be capable of matching published GitLab Reference Architecture benchmarks if you scale the instance resources to match the chosen benchmark.  If you are ready for production scale now (including scaled POCs), please follow the guides indicated below to scale it to your desire initial number of users from the start.

=== Sign in to your AWS account

Deployment takes about {deployment_time} to complete.

. Sign in to your AWS account at https://aws.amazon.com with an IAM user role that has the necessary permissions. For details, see link:#_planning_the_deployment[Planning the deployment] earlier in this guide.
. Make sure that your AWS account is configured correctly, as discussed in the link:#_technical_requirements[Technical requirements] section. 
. Ensure you have or know how to find the resource names, identifiers or arns discussed in the link:#_technical_requirements[Technical requirements] section.

=== Launch the Quick Start

NOTE: You are responsible for the cost of the AWS services used while running this Quick Start reference deployment. There is no additional cost for using this Quick Start. For full details, see the pricing pages for each AWS service used by this Quick Start. Prices are subject to change.

[start=4]
. Choose one of the following options to launch the AWS CloudFormation template. For help with choosing an option, see link:#_deployment_options[Deployment options] earlier in this guide.

[cols=2*]
|===
^|http://qs_launch_permalink[Deploy {partner-product-short-name} into a new VPC on AWS^]
^|http://qs_template_permalink[View template^]

^|http://qs_launch_permalink[Deploy {partner-product-short-name} into an existing VPC on AWS^]
^|http://qs_template_permalink[View template^]
|===

// Adapt the following warning to your Quick Start.
[WARNING]
====
If you’re deploying {partner-product-short-name} into an existing VPC, make sure that your VPC has two
private subnets in different Availability Zones for the workload instances and that the subnets aren’t shared. 
This Quick Start doesn’t support https://docs.aws.amazon.com/vpc/latest/userguide/vpc-sharing.html[shared subnets^]. 

These private subnets require https://docs.aws.amazon.com/vpc/latest/userguide/vpc-nat-gateway.html[NAT gateways^] 
in their route tables to allow the instances to download packages and software without exposing them to the internet. 
Also make sure that the domain name option in the DHCP options is configured as explained in 
http://docs.aws.amazon.com/AmazonVPC/latest/UserGuide/VPC_DHCP_Options.html[DHCP options sets^].  

The Quick Start uses Kubernetes integration with Elastic Load Balancing which requires each private subnet to 
be tagged with `kubernetes.io/role/internal-elb=true` and each public subnet with `kubernetes.io/role/elb=true`.

You provide your VPC settings when you launch the Quick Start.
====

[start=5]
. Check the AWS Region that’s displayed in the upper-right corner of the navigation bar, and change it if necessary. This Region is where the network infrastructure for {partner-product-short-name} is built (or expected to be if deploying into an existing VPC). The template is launched in the {default_deployment_region} Region by default.
. On the *Create stack* page, keep the default setting for the template URL, and then choose *Next*.
. On the *Specify stack details* page, change the stack name if needed. Review the parameters for the template. Provide values for the parameters that require input. For all other parameters, review the default settings and customize them as necessary. For details on each parameter, see the link:#_parameter_reference[Parameter reference] section of this guide. When you finish reviewing and customizing the parameters, choose *Next*.

NOTE: If GitLab is already deployed in your account, ensure that the `Per account shared resources` parameter 
is set to *No* or *AutoDetect*. If you deploy a new GitLab instance in the same Region as a previously deployed instance, 
set `Per region shared resources` to *No* or *AutoDetect*.

NOTE: Unless you are customizing this Quick Start's templates for your own deployment projects, we recommend that you keep the default settings for the parameters labeled `Quick Start S3 bucket name`, `Quick Start S3 bucket
Region`, and `Quick Start S3 key prefix`. Changing these parameter settings automatically updates code references to point to a new Quick Start location. For more information, see the https://aws-quickstart.github.io/option1.html[AWS Quick Start Contributor’s Guide^].

[start=8]
. On the *Configure stack options* page, you can https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-resource-tags.html[specify tags^] (key-value pairs) for resources in your stack and https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-console-add-tags.html[set advanced options^]. When you’re done, choose *Next*.

NOTE: If you wish to utilize cost management tags, you should add them in the step above.  They will also need to be activated in AWS Billing and Cost Management Console.

[start=9]
. On the *Review* page, review and confirm the template settings. Under *Capabilities*, select the two check boxes to acknowledge that the template creates IAM resources and might require the ability to automatically expand macros.
. Choose *Create stack* to deploy the stack.
ifndef::partner-product-short-name[. Monitor the status of the stack. When the status is *CREATE_COMPLETE*, the {partner-product-name} deployment is ready.]
ifdef::partner-product-short-name[. Monitor the status of the stack. When the status is *CREATE_COMPLETE*, the {partner-product-short-name} deployment is ready.]
. Use the values displayed in the *Outputs* tab for the stack, as shown in <<cfn_outputs>>, to view the created resources.

NOTE: Deployment takes about {deployment_time} to complete.