This Partner Solution deploys {partner-product-long-name} to the AWS Cloud. This Partner Solution is for users who want to deploy a production-grade {partner-product-short-name} instance. {partner-product-short-name} manages DevOps and other software development life cycles (SDLCs).

== Built-in value of AWS Partner Solutions

In addition to reference architecture compliance, this Partner Solution has these features:

=== Market reach and reuse

* An AWS Partner Solution (primary AWS use case): Provides production-grade high availability for third-party software. For more information, refer to https://aws.amazon.com/solutions/browse-all/?solutions-all.sort-by=item.additionalFields.headline&solutions-all.sort-order=asc&awsf.Content-Type=content-type%23quick-start&awsf.AWS-Product%20Category=*all[AWS Partner Solutions^].
* An AWS alternative to ServiceNow self-service automation: Customers and partners can create customized versions.
* AWS Control Tower: This allows vending of {partner-company-short-name} instances into AWS accounts that are managed by AWS Control Tower. For more information, refer to https://aws.amazon.com/controltower/partners/[AWS Control Tower Partners^].

=== Open-source community

* AWS Partner Solutions are open source.
* All Partner Solutions are quality tested using CI in multiple Regions when they're changed or when they take new versions of dependent Partner Solutions.
* Partner Solutions rely on included dependencies for Amazon Elastic Kubernetes Service (Amazon EKS), PostgreSQL, and others. These shared dependencies are used, debugged, and improved as community-maintained shared dependencies.
* The dependency framework provides EKS functionality that can be passed to the {partner-product-short-name} Partner Solution. For instance, support for EKS clusters on Amazon EC2 Spot Instances can be passed through for nonproduction setups like trainings and demonstrations.
