This Quick Start deploys {partner-product-long-name} on the AWS Cloud. This guide covers the steps necessary to deploy this Quick Start.

// For advanced information about the product, troubleshooting, or additional functionality, refer to the https://{quickstart-github-org}.github.io/{quickstart-project-name}/operational/index.html[Operational Guide^].

// For information about using this Quick Start for migrations, refer to the https://{quickstart-github-org}.github.io/{quickstart-project-name}/migration/index.html[Migration Guide^].

This Quick Start is for users who want a production grade {partner-product-short-name} instance deployed to AWS infrastructure.

{partner-product-short-name} is a single, open solution for managing DevOps and other software development life&#8209;cycles (SDLCs).

== Built-in value of AWS Quick Starts

In addition to reference architecture compliance, this Quick Start has these additional value-add features:

=== Market reach and reuse

* https://aws.amazon.com/quickstart/?solutions-all.sort-by=item.additionalFields.sortDate&solutions-all.sort-order=desc[As an AWS Quick Start] (primary use case initiated by AWS) - production grade HA&#8209;required 3rd party software deployable in the fewest possible clicks to AWS.
* https://aws.amazon.com/quickstart/?solutions-all.sort-by=item.additionalFields.sortDate&solutions-all.sort-order=desc[As an AWS service catalog item] - AWS alternative to ServiceNow self service automation - could be used by large customers or partners to create parameter customized versions
* https://aws.amazon.com/controltower/partners/[As an AWS Control Tower partner solution] - allowing vending of {partner-company-short-name} instances into AWS accounts managed by AWS Control Tower.

=== Open source community

* Quick Starts are managed as open source with special attention given by AWS Quick Start team and the vendor ({partner-company-short-name} in this case) whose software is the focus of the Quick Start.
* All Quick Starts are quality tested using CI in multiple regions when they are changed or when taking new versions of dependent Quick Starts.
* Relies on included Quick Start dependencies for Amazon EKS, PostgreSQL, and others. These shared dependencies are used, debugged and improved as community maintained shared dependencies that underlie many AWS Quick Starts.
* The value of the dependency framework is seen in that any of the EKS Quick Start functionality can be easily passed through to the {partner-product-short-name} Quick Start. For instance, support for EKS clusters on AWS Spot compute can be passed through for non-production setups like training and demos. The {partner-company-short-name} Quick Start depends on a few others that would also pass&#8209;through benefits.
