// Include any postdeployment steps here, such as steps necessary to test that the deployment was successful. If there are no postdeployment steps, leave this file empty.

== Postdeployment steps

When deployed for production grade implementations, this Quick Start does not setup {partner-product-short-name} Runners for you. To setup runners you can consult the https://docs.gitlab.com/runner/[{partner-product-short-name} Runner documentation^] or leverage the https://gitlab.com/guided-explorations/aws/gitlab-runner-autoscaling-aws-asg[{partner-product-short-name} HA Scaling Runner vending machine for AWS^]

=== First login

. Go to the https://console.aws.amazon.com/secretsmanager[AWS Secrets Manager console^] in the Region where {partner-product-short-name} was deployed and click on the secret ending in *initial-root-password*.
. Click the *Retrieve secret value* button.
. Decode the base64 encoded password with (the password will be in your copy / paste buffer):

.Bash command
[Source,bash]
----
echo {base64-encoded-password} | base64 -d | pbcopy
----

.PowerShell command
[Source,powsershell]
----
[Text.Encoding]::Utf8.GetString([Convert]::FromBase64String('{base64-encoded-password}')) | clip
----

[start=4]
. Copy the emitted password (or use your operating system's CLI command to pipe the above command output directly to the clipboard. Bash: `| pbcopy` PowerShell: `| clip`)
. Use an internet browser to access the {partner-product-short-name} instance URL.
. Login with the username 'root' and paste the password in.

[WARNING]
====
* If you get the error `Invalid Login or password.` you probably didn't use either the username 'root' for the username.
* If you get the error `This site can't be reached` you are probably not using the actual host name you put in your hosts file.
* If you get the message `default backend - 404` you probably forgot to prefix the domain with `gitlab.` in your hosts file and in your browser.
====

=== Accessing Kubernetes

NOTE: Using the bastion host for cluster administration has the following advantages: all the kubernetes utilities are pre-installed, it has permissions to the cluster and it is the only way to access the cluster if you setup the Quick Start to not expose a public endpoint for the cluster. If using the bastion host, complete these steps on that machine.

==== Connect to the bastion host

. Open the https://console.aws.amazon.com/ec2/v2/home?Instances:[Amazon EC2 Console^] in the Region where {partner-product-short-name} was deployed.
. Locate the instance named *EKSBastion*
. Right click it and select *Connect*
. On the *Connect to instance...* page, select the *Session Manager* tab.
. Click the orange *Connect* button.
. Wait for several seconds to be placed in a shell console.
. Switch to the root user where kubectl is preconfigured.

----
sudo su
----

[start=3]
. Test with this command:

----
/usr/local/bin/kubectl get pods --all-namespaces
----

=== Enable outbound email

Amazon Simple Email Service (Amazon SES) is purposely created in "sandbox" mode to prevent spam abuse using massively scaled email services. You must enable it manually.

. While logged into AWS, go to the https://console.aws.amazon.com/ses/[Amazon SES console^]^.
. On the left navigation, under *Email sending*, click **Sending statistics**
. On the right pane, next to *Production access*, visually validate that it says **Sandbox**.
. Click **Edit your account details** (button).
. Next to *Enable production access*, click **Yes**.
. For *Mail type* leave the default of **Transactional**.
. For *Website URL* enter **your {partner-product-short-name} instance URL**.
. Under *Use case description*, type **Testing {partner-product-short-name} instance outbound email**.
. Under *Additional contact addresses* type **your real email address**.
. Find *I agree to the AWS Service Terms and AUP*, and **check the box** to the right.
. Click **Submit for review**.

NOTE: Notice the new banner near the top containing *Your account details are currently under review*.

=== Accessing Grafana

. Go to the https://console.aws.amazon.com/secretsmanager[AWS Secrets Manager console^] in the region where {partner-product-short-name} was deployed and click on the secret ending in *initial-grafana-password*.
. Click the *Retrieve secret value* button.
. Decode the base64 encoded password with (the password will be in your copy / paste buffer):

.Bash command
[Source,bash]
----
echo {base64-encoded-password} | base64 -d | pbcopy
----

.PowerShell command
[Source,powsershell]
----
[Text.Encoding]::Utf8.GetString([Convert]::FromBase64String('{base64-encoded-password}')) | clip
----

. Visit **your {partner-product-short-name} URL** + /-/grafana.
. For user specify `root`.
. Use the password retrieved earlier.

=== Kubernetes cluster provisioning

{partner-product-short-name} can be configured to provision Amazon EKS clusters into AWS accounts. It requires configuration of an AWS IAM Role (and potentially an IAM user) for {partner-product-short-name} authentication in an AWS account. Each account where clusters will be provisioned also require at least one IAM Role for EKS cluster provisioning to be defined. For additional information, see the https://docs.gitlab.com/ee/user/project/clusters/add_eks_clusters.html#configure-amazon-authentication[{partner-product-short-name} documentation].

=== Integrating with existing clusters

A {partner-product-short-name} instance of any type (does not have to be running on Kubernetes) can integrate to a Kubernetes cluster for Review Apps and AutoDevOps to pre&#8209;production and production environments. For production deployments, the cluster containing your {partner-product-short-name} instance should not be used for this purpose due to the level of privileges required to deploy Review Apps and AutoDevOps to the cluster.

=== Operations

There are no specific things to account for in operating {partner-product-short-name} on AWS. When {partner-product-short-name} relies on AWS services like CloudWatch and S3, then the AWS&#8209;specific practices for those services are applicable, but as long as these services are correctly integrated, they are abstracted in {partner-product-short-name}. Services configuration may also provide benefits that are not anticipated by {partner-product-short-name}. For instance, using S3 storage policies for replicating backups to another region.

{partner-product-short-name} has distinctive SRE management concerns that will need to be monitored and adjusted. Aspects of {partner-product-short-name} operations can be impacted by instance type choices, provisioned IOPS, and other cloud&#8209;level implementation decisions.

{partner-product-short-name} provides the https://gitlab.com/gitlab-org/quality/performance[{partner-product-short-name} Performance Tool (gpt)^] and https://gitlab.com/gitlab-org/quality/performance/-/wikis/Benchmarks/Latest[Reference Architecture performance benchmarks^] created by the tool for the reference of {partner-product-short-name} instance site&#8209;reliability engineers (SREs). If your instance will be highly scaled, you should run the gpt tool against it for a baseline performance. This will help with scale planning.

Please consult the https://docs.gitlab.com[{partner-product-short-name} Documentation^] for general operations and usage information.

==== Log monitoring using CloudWatch Logs

----
aws logs tail --since 1d --follow /aws/log/path
----

==== Performance monitoring

===== Using CloudWatch Metrics

CloudWatch metrics are collected for instances and containers.  These metrics can be used for performance analysis, graphing, alarms and events in AWS CloudWatch. As per standard CloudWatch capabilities alarms and events can interact with many other AWS services for notifications or automated actions.

===== Using Prometheus

The Quick Start wires up {partner-product-short-name} to Prometheus deployed to the cluster to expose all {partner-product-short-name} surfaced application metrics. The Grafana deployment option enables "in&#8209;instance" Grafana capabilities with these metrics.

=== Security

The infrastructure that {partner-product-short-name} is deployed on must be secured according to that infrastructure's security best practices. {partner-product-short-name} has reasonable security out&#8209;of&#8209;the&#8209;box, but as with all complex products it can be configured with tighter security if required. For additional information, see the https://about.gitlab.com/blog/2020/05/20/gitlab-instance-security-best-practices/[security best practices^].

==== Public internet access

If the {partner-product-short-name} instance will be connected to the public internet, the industry advised security precautions and due diligences of public internet services should be applied to it, including (but not limited to), {partner-product-short-name} updates and patching and infrastructure updates and patching. Leveraging AWS hardened services for the front&#8209;end can help improve the security posture, such as, AWS Load Balancers, DNS, edge network services, SES for SMTP, et cetera).

The Quick Start does enable a more secure administrative mode by enabling the EKS cluster to be configured without a public endpoint and then configuring the Bastion host. The bastion host comes with cluster administration tools pre&#8209;installed such as kubectl, eksctl, AWS CLI, and Helm. The SSM agent is also pre&#8209;installed and SSM session manager permissions are configured. This means that even the Bastion host does not need to have a port publicly exposed in order to get a console session- either through the AWS Management Console or a workstation installation of the AWS CLI with the SSM extensions.

For production setups, {partner-product-short-name} Runner should not be deployed to the cluster that runs {partner-product-short-name}, *especially in privileged mode*.

{partner-product-short-name} publishes new releases (including security hotfixes) on the https://about.gitlab.com/releases/categories/releases/[Releases blog^].
