// Include any postdeployment steps here, such as steps necessary to test that the deployment was successful. If there are no postdeployment steps, leave this file empty.

== Postdeployment steps

This Partner Solution doesn't set up {partner-product-short-name} Runners for you when deployed for production-grade implementations. To set up Runners, refer to https://docs.gitlab.com/runner/[{partner-product-short-name} Runner^], or refer to https://gitlab.com/guided-explorations/aws/gitlab-runner-autoscaling-aws-asg[{partner-product-short-name} HA Scaling Runner Vending Machine for AWS EC2 ASG^].

=== Logging in

. Sign in to the AWS Management Console, and navigate to the https://console.aws.amazon.com/secretsmanager[AWS Secrets Manager Console^].
. On the top toolbar, choose the deployment's AWS Region.
. Choose the secret ending in *initial-root-password* (listed in <<secrets1>>).
. Choose *Retrieve secret value*.
. Decode the Base64-encoded password with one of the following commands (the password is in your copy–paste buffer):
+
.Bash command
[Source,bash]
----
echo {base64-encoded-password} | base64 -d | pbcopy
----
+
.PowerShell command
[Source,powsershell]
----
[Text.Encoding]::Utf8.GetString([Convert]::FromBase64String('{base64-encoded-password}')) | clip
----
+
[start=4]
+
. Copy the password, or use one of the following commands to pipe the previous command output directly to the clipboard:

     * Bash: `| pbcopy` 
     * PowerShell: `| clip`)
. Access the {partner-product-short-name} instance URL.
. Log in with the user name `root`, and paste in the password.

[WARNING]
====
* If you get the error *Invalid login or password*, verify that you used 'root' for the user name.
* If you get the error *This site can't be reached*, verify that you're using the host name from the hosts file.
* If you get the message *Default backend—404*, verify that you prefixed the domain with `gitlab.` in your hosts file and in your browser.
====

=== Accessing the EKS cluster

[TIP]
====
Use the bastion host for EKS cluster administration for the following advantages:

. Kubernetes cluster administration utilities are pre&#8209;installed.
. It has permissions to access the cluster.
. It provides access to the cluster if you configured the {partner-product-short-name} instance to not expose a public endpoint.
====

If you use the bastion host, complete these steps on that machine.

==== Connecting to the bastion host

. Sign in to the AWS Management Console, and navigate to https://console.aws.amazon.com/ec2/v2/home?Instances[Amazon EC2 Console^].
. On the top toolbar, choose the deployment's AWS Region.
. In the left navigation pane, choose *Instances*.
. On the *Instances* page, navigate to context menu for *EKSBastion*, and choose *Connect*.
. Choose the *Select Manager* tab.
. Choose *Connect*.
. Wait for several seconds to be placed in a shell console.
. Test the outcome by running the following command:

----
/usr/local/bin/kubectl get pods --all-namespaces
----

=== Enabling outbound email

Amazon Simple Email Service (Amazon SES) is purposely created in sandbox mode to prevent spam abuse. To enable it manually, complete the following steps:

. Sign in to the AWS Management Console, and navigate to https://console.aws.amazon.com/ses[Amazon SES console^]^.
. In the left navigation pane, choose *Account dashboard*.
. Under *Email sending*, choose *Sending statistics*.
. On the right pane, next to *Production access*, confirm that it says *Sandbox*.
. Choose *Edit your account details*.
. Next to *Enable production access*, choose *Yes*.
. For *Mail type*, keep the *Transactional* default value.
. For *Website URL*, enter your {partner-product-short-name} instance URL.
. Under *Use case description*, enter `Testing {partner-product-short-name} instance outbound email`.
. Under *Additional contact addresses*, enter your email address.
. Select *I agree to the AWS Service Terms and AUP*.
. Choose *Submit for review*.

NOTE: The new banner near the top should display *Your account details are currently under review*.

=== Accessing Grafana

. Sign in to the AWS Management Console, and navigate to https://console.aws.amazon.com/secretsmanager[AWS Secrets Manager Console^].
. On the top toolbar, choose the deployment's AWS Region.
. Choose the secret that ends with *initial-grafana-password*.
. Choose *Retrieve secret value*.
. Decode the Base64-encoded password using one of the following commands (the password is in your copy–paste buffer):
+
.Bash command
[Source,bash]
----
echo {base64-encoded-password} | base64 -d | pbcopy
----
+
.PowerShell command
[Source,powsershell]
----
[Text.Encoding]::Utf8.GetString([Convert]::FromBase64String('{base64-encoded-password}')) | clip
----
+
. Access your {partner-product-short-name} URL* + /-/grafana.
. Log in with the user name `root`.
. Use the password that you retrieved earlier.

=== Integrating Kubernetes

Integrate this Partner Solution with new or existing Kubernetes clusters.

==== Provisioning new Kubernetes clusters

You can configure {partner-product-short-name} to provision Amazon EKS clusters into AWS accounts. This requires configuration of an AWS IAM role (and potentially an IAM user) for {partner-product-short-name} authentication in an AWS account. Each account where clusters are provisioned also requires at least one IAM role for EKS cluster provisioning to be defined. For more information, refer to https://docs.gitlab.com/ee/user/project/clusters/add_eks_clusters.html#configure-amazon-authentication[Configure Amazon authentication^].

==== Integrating with existing Kubernetes clusters

A {partner-product-short-name} instance of any type (doesn't have to be running on Kubernetes) can integrate with a Kubernetes cluster for Review Apps and AutoDevOps to pre&#8209;production and production environments. For production deployments, the cluster containing your {partner-product-short-name} instance shouldn't be used for this purpose due to the level of permissions required to deploy Review Apps and AutoDevOps to the cluster.

==== Performance monitoring

Use Amazon CloudWatch or Prometheus to collect metrics.

===== Using Amazon CloudWatch metrics

Collect CloudWatch metrics for instances and containers. Use these metrics for performance analysis, graphing, alarms, and events. As per standard CloudWatch capabilities, alarms and events interact with other AWS services for notifications and automated actions.

===== Using Prometheus

To expose all {partner-product-short-name}–surfaced application metrics, this Partner Solution connects {partner-product-short-name} to Prometheus when deployed to the cluster. The Grafana deployment option enables in&#8209;instance Grafana capabilities with these metrics.
