//Include any predeployment steps here, such as signing up for a Marketplace AMI or making any changes to a partner account. If there are no predeployment steps, leave this file empty.

== Predeployment steps

Secure the infrastructure that {partner-product-short-name} is deployed on according to that infrastructure's security best practices.

=== Security considerations

 The {partner-product-short-name} Partner Solution incorporates general security best practices, but if you have specific requirements that aren't covered, you can customize the templates to meet your needs. For additional information, refer to the https://about.gitlab.com/blog/2020/05/20/gitlab-instance-security-best-practices/[{partner-product-short-name} instance: security best practices^].

==== Public internet access

WARNING: By default, the {partner-product-short-name} instance is configured with an internet ingress.

If the {partner-product-short-name} instance is connected to the public internet, apply the industry advised security precautions and due diligences of public internet services. This includes, {partner-product-short-name} and infrastructure updates and patching.

By default, the Partner Solution enables a secure administrative mode by configuring the EKS cluster without a public endpoint and a bastion host. The bastion host comes with cluster administration tools pre&#8209;installed such as kubectl, eksctl, AWS CLI, and Helm. The Partner Solution pre&#8209;installs the SSM agent and configures the SSM session manager permissions. The bastion host doesn't need to have a port publicly exposed to get a console session, either through the AWS Management Console or a workstation installation of the AWS CLI with the SSM extensions.

For production setups, don't deploy {partner-product-short-name} Runner to the cluster that runs {partner-product-short-name}, especially in privileged mode.

{partner-product-short-name} publishes new releases (including security hotfixes) on the https://about.gitlab.com/releases/categories/releases/[Releases blog^].

=== Instance version selection

The version of {partner-product-short-name} that's deployed depends on the {partner-product-short-name} Helm chart version you select when you launch this Partner Solution. For additional information, see the https://docs.gitlab.com/charts/installation/version_mappings.html[{partner-product-short-name} chart versions^].

=== Migration considerations

WARNING: If you're migrating an existing {partner-product-short-name} instance to one built by this Partner Solution, it's critical to have the new instance version match the old instance version during migration. You can upgrade the {partner-product-short-name} version on the old instance before migration or on the new instance after migration, but not during a migration using mismatched versions. This includes the versions of all underlying components such as PostgreSQL and Redis.

=== Component sizing

This Partner Solution creates {partner-product-short-name} cloud native reference architecture-compliant {partner-product-short-name} instances. {partner-product-short-name} reference architectures have a "Cloud Native Hybrid" section that has a manifest of required resources to use while deploying the template. For additional information, refer to https://docs.gitlab.com/ee/install/aws/gitlab_hybrid_on_aws.html#gitlab-cloud-native-hybrid-on-aws[GitLab Cloud Native Hybrid on AWS^].

=== Post-installation considerations

Once operational, if you intend to integrate the {partner-product-short-name} instance with one or more new or existing Kubernetes cluster, see the following sections to ensure you configure the {partner-product-short-name} instance appropriately:

* <<Provisioning new Kubernetes clusters>>
* <<Integrating with existing Kubernetes clusters>>

==== Deploying {partner-product-short-name} Runners

For a production deployment, don't deploy the Kubernetes Runner chart integrated into the Partner Solution because it deploys to the same cluster as {partner-product-short-name} and creates workload scaling challenges. Don't enable privileged mode because it gives very high privileges to the cluster for any Runner job. We advise a separate {partner-product-short-name} Runner design and deployment because without privileged mode, AutoDevOps, Review Apps and DinD based container builds won't work (Kaniko based container builds can work).

Alternative {partner-product-short-name} Runner deployment options include:

. For groups and projects that are integrated into a Kubernetes cluster dedicated to development and/or production, you can deploy the GitLab Runner as a managed app. Refer to https://docs.gitlab.com/ee/user/infrastructure/clusters/manage/management_project_applications/runner.html[Install {partner-product-short-name} Runner with a cluster management project^] or use the https://docs.gitlab.com/runner/install/kubernetes.html[{partner-product-short-name} Runner Helm Chart^] after the clusters are integrated.
. For non-Kubernetes integrated groups or projects or for shared runners for the entire instance, use the https://gitlab.com/guided-explorations/aws/gitlab-runner-autoscaling-aws-asg[{partner-product-short-name} HA Scaling Runner Vending Machine for AWS EC2 ASG^] to deploy runners of all OS types and Runner Executor types using an AWS ASG.
. Implement a dedicated EKS cluster for a fleet of shared runners.
