//Include any predeployment steps here, such as signing up for a Marketplace AMI or making any changes to a partner account. If there are no predeployment steps, leave this file empty.

== Predeployment steps

=== Security considerations

The infrastructure that {partner-product-short-name} is deployed on must be secured according to that infrastructure's security best practices. The {partner-product-short-name} Quick Start incorporates general security best practices, but if you have specific requirements that aren't covered, the templates can be customized to meet your needs. For additional information, see the https://about.gitlab.com/blog/2020/05/20/gitlab-instance-security-best-practices/[security best practices^].

==== Public internet access

WARNING: The {partner-product-short-name} instance will be configured with an internet ingress by default.

If the {partner-product-short-name} instance will be connected to the public internet, the industry advised security precautions and due diligences of public internet services should be applied to it, including (but not limited to), {partner-product-short-name} updates and patching and infrastructure updates and patching. Leveraging AWS hardened services for the front&#8209;end can help improve the security posture, such as, AWS Load Balancers, DNS, edge network services, SES for SMTP, et cetera).

By default, the Quick Start enables a secure administrative mode by configuring the EKS cluster without a public endpoint and a bastion host. The bastion host comes with cluster administration tools pre&#8209;installed such as kubectl, eksctl, AWS CLI, and Helm. The SSM agent is also pre&#8209;installed and SSM session manager permissions are configured. This means that even the bastion host does not need to have a port publicly exposed in order to get a console session- either through the AWS Management Console or a workstation installation of the AWS CLI with the SSM extensions.

For production setups, {partner-product-short-name} Runner should not be deployed to the cluster that runs {partner-product-short-name}, *especially in privileged mode*.

{partner-product-short-name} publishes new releases (including security hotfixes) on the https://about.gitlab.com/releases/categories/releases/[Releases blog^].

=== Instance version selection

The version of {partner-product-short-name} that will be deployed depends on the {partner-product-short-name} Helm chart version you select when launching this Quick Start. For additional information about mapping {partner-product-short-name} Helm chart versions to {partner-product-short-name} product versions, see the https://docs.gitlab.com/charts/installation/version_mappings.html[documentation^].

=== Migration considerations

WARNING: If you are migrating an existing {partner-product-short-name} instance to one built by this Quick Start, it is critical to have the new instance version match the old instance version during migration. {partner-product-short-name} version upgrades can be done on the old instance before migration or on the new instance after migration, but not during a migration using mismatched versions. This includes the versions of all underlying components such as PostgreSQL and Redis.

=== Component sizing

This Quick Start is capable of creating {partner-product-short-name} cloud native reference architecture compliant {partner-product-short-name} instances. {partner-product-short-name} reference architectures have a "Cloud Native Hybrid" section that gives a manifest of required resources that can be used while deploying the template. For additional information, see the https://docs.gitlab.com/ee/install/aws/gitlab_hybrid_on_aws.html#gitlab-cloud-native-hybrid-on-aws[documentation].

=== Post-installation considerations

==== Kubernetes considerations

If you intend to integrate the {partner-product-short-name} instance with one or more new or existing Kubernetes cluster once operational, see the following sections to ensure your {partner-product-short-name} instance is configured appropriately:

* <<Provisioning new Kubernetes clusters>>
* <<Integrating with existing Kubernetes clusters>>

==== Deploying {partner-product-short-name} Runners

For a production deployment, the Kubernetes Runner chart integrated into the Quick Start should not be deployed because it deploys to the same cluster as {partner-product-short-name}. This can create workload scaling challenges and should never be done with privileged mode enabled because it gives very high privileges to the cluster for any Runner job. However, without privileged mode, AutoDevOps, Review Apps and DinD based container builds will not work (Kaniko based container builds can work) - so a separate {partner-product-short-name} Runner design and deployment is advised.

Alternative {partner-product-short-name} Runner deployment options include:

. For groups and projects that will be integrated into a Kubernetes cluster dedicated to development and/or production, the https://docs.gitlab.com/ee/user/clusters/applications.html#gitlab-runner[{partner-product-short-name} Runner can be deployed as a managed app^] or using the https://docs.gitlab.com/runner/install/kubernetes.html[Runner Helm chart^] after the clusters are integrated.
. For non-Kubernetes integrated groups, projects or for shared runners for the entire instance, the https://gitlab.com/guided-explorations/aws/gitlab-runner-autoscaling-aws-asg[{partner-product-short-name} HA scaling Runner vending machine for AWS^] can be used to deploy runners of all OS types and Runner Executor types using an AWS ASG.
. Another option is to implement a dedicated EKS cluster for a fleet of shared runners.
