//Include any predeployment steps here, such as signing up for a Marketplace AMI or making any changes to a partner account. If there are no predeployment steps, leave this file empty.

== Predeployment steps

Secure the {partner-product-short-name}–deployed infrastructure according to best practices.

=== Security considerations

The {partner-product-short-name} Partner Solution incorporates general security best practices, but if you have specific requirements that aren't covered, you can customize the templates to meet your needs. For more information, refer to https://about.gitlab.com/blog/2020/05/20/gitlab-instance-security-best-practices/[{partner-product-short-name} instance: security best practices^].

==== Public internet access

WARNING: By default, the {partner-product-short-name} instance is configured for inbound traffic.

If the {partner-product-short-name} instance is connected to the public internet, apply the industry-advised security precautions of public internet services. This includes {partner-product-short-name} and infrastructure updates and patching.

By default, the Partner Solution enables a secure administrative mode by configuring the EKS cluster without a public endpoint and bastion host. The bastion host comes with cluster administration tools preinstalled, such as Kubectl, Eksctl, AWS CLI, and Helm. The Partner Solution preinstalls the AWS Systems Manager agent and configures the session manager permissions. The bastion host doesn't need a publicly exposed port for a console session, either through the AWS Management Console or a workstation installation of the AWS CLI with the AWS Systems Manager extensions.

For production setups, don't deploy {partner-product-short-name} Runner to the cluster it runs on, especially in privileged mode. {partner-product-short-name} publishes new releases (including security hotfixes) on the https://about.gitlab.com/releases/categories/releases/[Releases blog^].

=== Instance version selection

The version of {partner-product-short-name} that's deployed depends on the Helm chart version you chose at launch time. For more information, refer to the https://docs.gitlab.com/charts/installation/version_mappings.html[{partner-product-short-name} chart versions^].

=== Migration considerations

WARNING: If you're migrating an existing {partner-product-short-name} instance to one built by this Partner Solution, the new instance version must match the old instance version during migration. You can upgrade the {partner-product-short-name} version on the old instance before migration—or on the new instance after migration—but not during a migration using mismatched versions. This includes the versions of all underlying components, such as PostgreSQL and Redis.

=== Component sizing

This Partner Solution creates {partner-product-short-name} architecture-compliant {partner-product-short-name} instances. {partner-product-short-name} reference architectures have a hybrid section that has a manifest of required resources to use while deploying the template. For more information, refer to https://docs.gitlab.com/ee/install/aws/gitlab_hybrid_on_aws.html#gitlab-cloud-native-hybrid-on-aws[GitLab Cloud Native Hybrid on AWS^].

=== Postinstallation considerations

If you intend to integrate the {partner-product-short-name} instance with one or more new or existing Kubernetes clusters, refer to the following sections to ensure you configure the {partner-product-short-name} instance properly:

* <<Provisioning new Kubernetes clusters>>
* <<Integrating with existing Kubernetes clusters>>

==== Deploying {partner-product-short-name} Runners

For a production deployment, don't deploy the Kubernetes Runner chart integrated into the Partner Solution because it deploys to the same cluster as {partner-product-short-name} and creates workload scaling challenges. Don't enable privileged mode because it grants high-level permissions to the cluster for any Runner job. We advise a separate {partner-product-short-name} Runner design and deployment because without privileged mode, AutoDevOps, Review Apps, and DinD-based container builds won't work. Kaniko-based container builds, however, do work.

Alternative {partner-product-short-name} Runner deployment options include the following:

. For groups and projects that are integrated into a Kubernetes cluster dedicated to development or production, you can deploy the GitLab Runner as a managed application. After the clusters are integrated, refer to https://docs.gitlab.com/ee/user/infrastructure/clusters/manage/management_project_applications/runner.html[Install {partner-product-short-name} Runner with a cluster management project^], or use the https://docs.gitlab.com/runner/install/kubernetes.html[{partner-product-short-name} Runner Helm Chart^].
. For non-Kubernetes-integrated groups or projects, or for shared runners for the entire instance, use the https://gitlab.com/guided-explorations/aws/gitlab-runner-autoscaling-aws-asg[{partner-product-short-name} HA Scaling Runner Vending Machine for AWS EC2 ASG^] to deploy runners of all OS types and Runner executor types using an AWS Auto Scaling Group.
. Implement a dedicated EKS cluster for a fleet of shared runners.
