// Add any unique troubleshooting steps here.

For troubleshooting common Quick Start issues, refer to the https://fwd.aws/rA69w?[AWS Quick Start General Information Guide^] and https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/troubleshooting.html[Troubleshooting CloudFormation^].

== Additional information

There are no specific things to account for in operating {partner-product-short-name} on AWS. When {partner-product-short-name} relies on AWS services like CloudWatch and S3, then the AWS&#8209;specific practices for those services are applicable, but as long as these services are correctly integrated, they are abstracted in {partner-product-short-name}. Utilizing AWS services offers features for covering use cases out of scope of the {partner-product-short-name} solution, such as using S3 storage policies for replicating backups to another region.

{partner-product-short-name} has distinctive site&#8209;reliability engineering (SRE) management concerns that will need to be monitored and adjusted. Aspects of {partner-product-short-name} operations can be impacted by https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/instance-types.html[Amazon EC2 instance type] choices, https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/provisioned-iops.html[Amazon EBS Provisioned IOPS], and other cloud&#8209;level implementation decisions.

{partner-product-short-name} provides the https://gitlab.com/gitlab-org/quality/performance[{partner-product-short-name} Performance Tool (gpt)^] and https://gitlab.com/gitlab-org/quality/performance/-/wikis/Benchmarks/Latest[Reference Architecture performance benchmarks^] created by the tool for the reference of {partner-product-short-name} instance SREs. If you need to scale your instance, you should run the gpt tool against it for a baseline performance. This will help with scale planning.

Please consult the https://docs.gitlab.com[{partner-product-short-name} documentation^] for general operations and usage information.

// == Resources
// Uncomment section and add links to any external resources that are specified by the partner.
